apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-deployment
  labels:
    app: static-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: static-website
        image: your-dockerhub-username/static-website:latest  # Replace with your Docker image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html  # This is the default directory for Nginx to serve files
      volumes:
      - name: website-content
        emptyDir: {}  # This volume will be used to store content for serving via Nginx
